[package]
name = "geyser-grpc-plugin-client"
version =  { workspace = true }
authors =  { workspace = true }
license =  { workspace = true }
edition =  { workspace = true }

[dependencies]
jito-geyser-protos = { workspace = true }
jito-solana-sdk = { workspace = true, optional = true }
log = { workspace = true }
lru = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
solana-sdk = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true, features = ["tls"] }

[build-dependencies]
tonic-build = { workspace = true }

[features]
jito-solana = ["jito-solana-sdk"]
