[package]
name = "jito-geyser-protos"
version =  { workspace = true }
authors =  { workspace = true }
license =  { workspace = true }
edition =  { workspace = true }
description = "Jito's Solana geyser protobufs and helper libraries"

[dependencies]
bincode = { workspace = true }
jito-solana-account-decoder = { workspace = true, optional = true }
jito-solana-sdk = { workspace = true, optional = true }
jito-solana-transaction-status = { workspace = true, optional = true }
prost =  { workspace = true }
prost-types =  { workspace = true }
serde =  { workspace = true }
solana-account-decoder =  { workspace = true }
solana-sdk =  { workspace = true }
solana-transaction-status =  { workspace = true }
tonic =  { workspace = true }

[build-dependencies]
tonic-build =  { workspace = true }

[features]
jito-solana = ["jito-solana-account-decoder", "jito-solana-sdk", "jito-solana-transaction-status"]
