name: Clean Code Check
on:
  workflow_call:

jobs:
  clippy_and_udeps_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          caller-workflow-name: clippy_and_udeps_check

      - name: Setup Rust tools
        run: cargo install cargo-sort cargo-udeps --locked

      - name: Cargo sort
        run: cargo +stable sort --workspace --check

      - name: Clippy udeps
        run: cargo +nightly udeps --workspace --all-features --all-targets --tests

      - name: Clippy Check
        run: cargo +nightly clippy --all-features --all-targets --tests